# Generated by Django 3.0.6 on 2020-05-10 19:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dateTimeCreated', models.DateTimeField(auto_now=True)),
                ('amountOutstanding', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('dateTimeCreated', models.DateTimeField(auto_now=True)),
                ('isRecurring', models.BooleanField()),
                ('freqOfRecurrence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('itemsOrdered', models.TextField()),
                ('amountDue', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amountOutstanding', models.DecimalField(decimal_places=2, max_digits=9)),
                ('orderStatus', models.TextField()),
                ('dateTimeCreated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dateTimeCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Vendor'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('dateTimeCreated', models.DateTimeField(auto_now=True)),
                ('messageStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.MessageStatus')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Order')),
                ('subjecteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='vendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Vendor'),
        ),
    ]
